### ISSUE TITLE
FileNotFoundError: .npy files are missing

### ISSUE THREAD

**Issue by wardaddy24** [siyuhuang/PoseStylizer#12]
I was trying to do inference on the deep fashion but the .npy files seem to be missing. These are not present in the google drive links also. Can you please tell me the format of data inside the .npy file and how it is generated?

`WEB_DIR: ./results/fashion_APS/test_latest
testing samples: 100000/8570
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    for i, data in enumerate(dataset):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/pose-compute/code/Users/Aman.Rastogi/PoseStylizer/data/custom_dataset_data_loader.py", line 42, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/anaconda/envs/posestylizer/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/anaconda/envs/posestylizer/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/anaconda/envs/posestylizer/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/anaconda/envs/posestylizer/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/pose-compute/code/Users/Aman.Rastogi/PoseStylizer/data/keypoint.py", line 49, in __getitem__
    BP1_img = np.load(BP1_path) # h, w, c
  File "/anaconda/envs/posestylizer/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/fashion_data/testK/fashionWOMENBlouses_Shirtsid0000337203_3back.jpg.npy'`

**Comment by siyuhuang** [comment]
See Data Preperation 2 in Readme
